#ifndef CASMJIT_X86_REGS_H
#define CASMJIT_X86_REGS_H

typedef enum {
    REG_AL = 0x00,
    REG_CL,
    REG_DL,
    REG_BL,
    REG_R8B = 0x08,
    REG_R9B,
    REG_R10B,
    REG_R11B,
    REG_R12B,
    REG_R13B,
    REG_R14B,
    REG_R15B,
    REG_SPL = 0x14,
    REG_BPL,
    REG_SIL,
    REG_DIL,
    REG_AH = 0x24,
    REG_CH,
    REG_DH,
    REG_BH,
    REG_AX = 0x40,
    REG_CX,
    REG_DX,
    REG_BX,
    REG_SP,
    REG_BP,
    REG_SI,
    REG_DI,
    REG_R8W = 0x48,
    REG_R9W,
    REG_R10W,
    REG_R11W,
    REG_R12W,
    REG_R13W,
    REG_R14W,
    REG_R15W,
    REG_EAX = 0x80,
    REG_ECX,
    REG_EDX,
    REG_EBX,
    REG_ESP,
    REG_EBP,
    REG_ESI,
    REG_EDI,
    REG_R8D = 0x88,
    REG_R9D,
    REG_R10D,
    REG_R11D,
    REG_R12D,
    REG_R13D,
    REG_R14D,
    REG_R15D,
    REG_RAX = 0xC0,
    REG_RCX,
    REG_RDX,
    REG_RBX,
    REG_RSP,
    REG_RBP,
    REG_RSI,
    REG_RDI,
    REG_R8 = 0xC8,
    REG_R9,
    REG_R10,
    REG_R11,
    REG_R12,
    REG_R13,
    REG_R14,
    REG_R15,
    REG_INVD = 0xFF,
} genreg_t;

#define REG_SIZE(r) (((r) >> 6) & 3)
#define REG_REXW(r) (REG_SIZE(r) == 3)
#define REG_OP16(r) (REG_SIZE(r) == 1)
#define REG_LOW3(r) ((r) & 0x07)
#define REG_NUM(r) ((r) & 0x0F)
#define REG_EXT(r) (((r) >> 3) & 1)

#endif // CASMIJIT_X86_REGS_H
